# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pos <- function(phrase) {
	if(Sys.info()["sysname"] == "Darwin" | Sys.info()["sysname"] == "Linux") {
		dicpath <- "/usr/local/lib/mecab/dic/mecab-ko-dic"
		if(dir.exists(dicpath)) {
		dicpath <- paste0("-d ", dicpath)
		} else {
		stop(paste0("Mecab-ko-dic is not found on ", dirpath, ". Please check https://bitbucket.org/eunjeon/mecab-ko-dic."))
		}
	} else {
		stop("Eunjeon project supports Mac, Linux, and Windows only.")
	}

	# TODO: Support Windows with mecab-ko-msvc
	# else if(Sys.info()["sysname"] == "Windows") {
	# 	 dicpath <- "C:\\mecab\\mecab-ko-dic"
	# 	 if(dir.exists(dicpath)) {
	#		 dicpath <- paste0("-d ", dicpath)
	#	 } else {
	#		 stop(paste0("Mecab-ko-dic is not found on ", dicpath, ". Please check https://github.com/Pusnow/mecab-ko-dic-msvc."))
	#	 }

	if (typeof(phrase) != "list") {
  		# type coersion to the list
  		phrase <- as.list(phrase)
  	}
  	tagged <- posRcpp(phrase, dicpath)
	names(tagged) <- phrase
	return(tagged)
}
