# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simple_ngrams <- function(tokenized_list, n, stopwords = character(), ngram_delim = " ") {
    .Call('_RmecabKo_simple_ngrams', PACKAGE = 'RmecabKo', tokenized_list, n, stopwords, ngram_delim)
}

nounsRcpp <- function(phrase, dic) {
    .Call('_RmecabKo_nounsRcpp', PACKAGE = 'RmecabKo', phrase, dic)
}

wordsRcpp <- function(phrase, dic) {
    .Call('_RmecabKo_wordsRcpp', PACKAGE = 'RmecabKo', phrase, dic)
}

posRcpp <- function(phrase, dic, join) {
    .Call('_RmecabKo_posRcpp', PACKAGE = 'RmecabKo', phrase, dic, join)
}

