# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simple_ngrams <- function(tokenized_list, n_values, skip_values, stopwords, ngram_delim) {
    .Call(`_RmecabKo_simple_ngrams`, tokenized_list, n_values, skip_values, stopwords, ngram_delim)
}

