# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nounsRcpp <- function(phrase, dic) {
    .Call('_RmecabKo_nounsRcpp', PACKAGE = 'RmecabKo', phrase, dic)
}

posRcpp <- function(phrase, dic) {
    .Call('_RmecabKo_posRcpp', PACKAGE = 'RmecabKo', phrase, dic)
}

